media:
  input: public
  output: /
  label: Media

content:
  - name: home
    label: Home
    type: file
    path: src/content/home/home.json
    fields:
      - name: name
        label: Name
        type: string

      - name: tagline
        label: Tagline
        type: string

      - name: introImages
        label: Intro images
        type: object
        list: true
        fields:
          - name: src
            label: Image
            type: image
            directory: public/images
            publicPath: /images
          - name: alt
            label: Alt text
            type: string

      - name: heroTitle
        label: Hero title
        type: string

      - name: heroSubtitle
        label: Hero subtitle
        type: text

      - name: heroImage
        label: Hero Image
        type: image
        directory: public/uploads
        publicPath: /uploads

      - name: resumeUrl
        label: Resume URL
        type: string

  # About page content (single JSON file)
  - name: about
    label: About
    type: file
    path: src/content/about/about.json
    fields:
      - name: aboutText
        label: About text
        type: text

  # Projects content folder (multiple JSON files)
  - name: projects
    label: Projects
    type: collection
    path: src/content/projects
    format: json
    filename: "{primary}.json"

    view:
      fields: [title]

    fields:
      - name: title
        label: Project title
        type: string

      - name: shortDescription
        label: Short description
        type: text

      - name: description
        label: Description
        type: text

      - name: logo
        label: Logo
        type: image
        directory: public/images/logos
        publicPath: /images/logos

      - name: images
        label: Images
        type: object
        list: true
        fields:
          - name: src
            label: Image
            type: image
            directory: public/images
            publicPath: /images

          - name: caption
            label: Caption
            type: string
